# Generated by Django 6.0.2 on 2026-02-11 04:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_contacts', models.IntegerField(default=0, verbose_name='Total Contacts')),
                ('contacts_added_today', models.IntegerField(default=0, verbose_name='Contacts Added Today')),
            ],
            options={
                'verbose_name': 'Contact Statistics',
                'verbose_name_plural': 'Contact Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('whatsapp_contact', models.CharField(help_text='Include country code, e.g., +233XXXXXXXXX', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp Contact')),
                ('category', models.CharField(choices=[('face_card', 'Face Card'), ('chubby', 'Chubby'), ('brand_owner', 'Brand Owner'), ('slim', 'Slim'), ('curvy', 'Curvy'), ('dark_skin', 'Dark Skin'), ('half_cast', 'Half Cast')], max_length=50, verbose_name='Category')),
                ('age_category', models.CharField(choices=[('18-24', '18-24'), ('25-30', '25-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41+', '41+')], max_length=10, verbose_name='Age Category')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, help_text='e.g., +233, +1, +44', max_length=5, verbose_name='Country Code')),
                ('social_media_platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=20, verbose_name='Social Media Platform')),
                ('social_media_handle', models.CharField(blank=True, max_length=100, verbose_name='Social Media Handle')),
                ('followers_count', models.IntegerField(default=0, help_text='Current follower count', verbose_name='Followers Count')),
                ('school', models.CharField(blank=True, max_length=200, null=True, verbose_name='School')),
                ('level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Level/Grade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('whatsapp_message_sent', models.BooleanField(default=False, verbose_name='WhatsApp Message Sent')),
                ('whatsapp_message_date', models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Message Date')),
                ('synced_to_drive', models.BooleanField(default=False, verbose_name='Synced to Google Drive')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-followers_count', '-date_added'],
                'indexes': [models.Index(fields=['category'], name='contacts_co_categor_66a73d_idx'), models.Index(fields=['country'], name='contacts_co_country_aaeb10_idx'), models.Index(fields=['social_media_platform'], name='contacts_co_social__580f3f_idx'), models.Index(fields=['-followers_count'], name='contacts_co_followe_185e15_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('whatsapp', 'WhatsApp Message'), ('drive_sync', 'Google Drive Sync'), ('export', 'Data Export')], max_length=20, verbose_name='Action Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='contacts.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
