# Generated by Django 6.0.2 on 2026-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='age_category',
            field=models.CharField(choices=[('18-24', '18 – 24'), ('25-30', '25 – 30'), ('31-35', '31 – 35'), ('36-40', '36 – 40'), ('41-45', '41 – 45'), ('46-50', '46 – 50'), ('51-55', '51 – 55'), ('56-60', '56 – 60'), ('60+', '60+')], max_length=10, verbose_name='Age Category'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, help_text='e.g., +233, +1, +44', max_length=10, verbose_name='Country Code'),
        ),
    ]
