# Generated by Django 6.0.2 on 2026-03-07 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_age_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from the registration form without deleting it. It stays in downloaded contact data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Short identifier used in the URL parameter e.g. 'ig-bio'", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable label e.g. 'Instagram Bio Link'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referral Source',
                'verbose_name_plural': 'Referral Sources',
                'ordering': ['label'],
            },
        ),
        migrations.RemoveField(
            model_name='automationlog',
            name='contact',
        ),
        migrations.DeleteModel(
            name='ContactStats',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_categor_66a73d_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_country_aaeb10_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_social__580f3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_followe_185e15_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='age_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='follower_range',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under 5K'), ('5k-10k', '5K – 10K'), ('10k-50k', '10K – 50K'), ('50k-100k', '50K – 100K'), ('100k-250k', '100K – 250K'), ('250k-500k', '250K – 500K'), ('500k-1M', '500K – 1M'), ('1M+', '1M+')], max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='handle',
            field=models.CharField(blank=True, help_text='Stored without @ prefix.', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='level_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year or level as a number only.', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='referral_slug',
            field=models.CharField(blank=True, help_text='Raw slug captured from ?ref= URL parameter at registration.', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='region',
            field=models.CharField(blank=True, help_text='Broad regional area, not a specific town.', max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='school_category',
            field=models.CharField(blank=True, choices=[('basic', 'Basic School'), ('high_school', 'High School'), ('tertiary', 'Tertiary')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Stored as full international number e.g. +233241234567', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, help_text='Auto-filled from the WhatsApp country code selector.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, help_text='Dial code e.g. +233. Auto-set from WhatsApp selector.', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', help_text='Used to prevent duplicate registrations.', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Selected in the optional pop-up during registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.category'),
        ),
        migrations.AddField(
            model_name='contact',
            name='referral_source',
            field=models.ForeignKey(blank=True, help_text='Which link/platform brought this person here.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.referralsource'),
        ),
        migrations.DeleteModel(
            name='AutomationLog',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='age_category',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='level',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='school',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_media_handle',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_media_platform',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='synced_to_drive',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp_contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp_message_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp_message_sent',
        ),
    ]
