# Generated by Django 6.0.2 on 2026-05-15 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_googletoken_referralsource_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='follower_range',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under 5K'), ('5k-10k', '5K â€“ 10K'), ('10k-50k', '10K â€“ 50K'), ('50k-100k', '50K â€“ 100K'), ('100k-250k', '100K â€“ 250K'), ('250k-500k', '250K â€“ 500K'), ('500k-1M', '500K â€“ 1M'), ('1M+', '1M+')], max_length=50),
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('fallback', 'SMS Fallback')], default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.contact')),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
