# Generated by Django 6.0.2 on 2026-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_servicerequest_bulkmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agreed_to_terms',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
