# Generated by Django 6.0.2 on 2026-05-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='follower_range',
            field=models.CharField(blank=True, choices=[('under_5k', 'Under 5K'), ('5k-10k', '5K – 10K'), ('10k-50k', '10K – 50K'), ('50k-100k', '50K – 100K'), ('100k-250k', '100K – 250K'), ('250k-500k', '250K – 500K'), ('500k-1M', '500K – 1M'), ('1M+', '1M+')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['date_added'], name='contacts_co_date_ad_d53fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['country'], name='contacts_co_country_aaeb10_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['platform'], name='contacts_co_platfor_959a93_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['whatsapp_number'], name='contacts_co_whatsap_934ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contacts_co_email_25f973_idx'),
        ),
    ]
