# Generated by Django 6.0.2 on 2026-06-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_contact_follower_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('wadm', 'WhatsApp DM'), ('wach', 'WhatsApp Channel'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('snapchat', 'Snapchat')], max_length=20, unique=True)),
                ('handle', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('followers', models.CharField(blank=True, max_length=50)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('announcement', 'Announcement'), ('campaign', 'Campaign'), ('milestone', 'Milestone'), ('testimonial', 'Testimonial'), ('video', 'Video')], default='announcement', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Complete')], default='draft', max_length=20)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('contacted_count', models.PositiveIntegerField(default=0)),
                ('responded_count', models.PositiveIntegerField(default=0)),
                ('confirmed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_categories', models.ManyToManyField(blank=True, to='contacts.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
