# Generated by Django 6.0.2 on 2026-06-10 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_whatsapptemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.CharField(blank=True, help_text="For testimonials: format as 'Name, Location' e.g. 'Abena K., Accra'", max_length=200),
        ),
        migrations.CreateModel(
            name='CategoryChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=25)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('current_category', models.CharField(blank=True, help_text='Auto-populated from the contact record at time of request.', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='contacts.category')),
            ],
            options={
                'verbose_name': 'Category Change Request',
                'verbose_name_plural': 'Category Change Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
