# Generated by Django 6.0.2 on 2026-06-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_communitypost_author_categorychangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_message',
            field=models.TextField(blank=True),
        ),
    ]
