# Generated by Django 6.0.2 on 2026-06-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_campaign_campaign_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='contacts.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='contacts.contact')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
