# Generated by Django 6.0.2 on 2026-06-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_campaigncontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='direction',
            field=models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], default='out', max_length=5),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='message_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whatsapplog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('fallback', 'SMS Fallback'), ('received', 'Received')], default='sent', max_length=20),
        ),
    ]
