# Generated by Django 6.0.2 on 2026-07-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
