# Generated by Django 6.0.2 on 2026-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='media_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
