# Generated by Django 6.0.2 on 2026-08-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_whatsapplog_media_type_whatsapplog_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplog',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
    ]
