# Generated by Django 6.0.2 on 2026-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_whatsapplog_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='stat_contacts',
            field=models.PositiveIntegerField(default=12842, help_text='Registered Contacts number shown on the public landing page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_countries',
            field=models.PositiveIntegerField(default=5, help_text='Countries Connected number shown on the public landing page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_organizations',
            field=models.PositiveIntegerField(default=568, help_text='Organizations number shown on the public landing page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_regions',
            field=models.PositiveIntegerField(default=16, help_text='Regions Covered number shown on the public landing page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_schools',
            field=models.PositiveIntegerField(default=1245, help_text='Schools number shown on the public landing page.'),
        ),
    ]
