with open('contacts/views/bulk.py', 'w', encoding='utf-8') as f:
    f.write(
        '# contacts/views/bulk.py\n'
        'import time\n'
        'from django.contrib import messages\n'
        'from django.contrib.auth.decorators import login_required\n'
        'from django.http import JsonResponse\n'
        'from django.shortcuts import redirect, render\n'
        'from ..models import BulkMessage, Contact, ServiceRequest\n'
        '\n'
        '\n'
        '@login_required(login_url="login")\n'
        'def bulk_compose_view(request):\n'
        '    qs = Contact.objects.all()\n'
        '    category = request.GET.get("category", "").strip()\n'
        '    country  = request.GET.get("country",  "").strip()\n'
        '    platform = request.GET.get("platform", "").strip()\n'
        '    if category: qs = qs.filter(category__name__iexact=category)\n'
        '    if country:  qs = qs.filter(country__iexact=country)\n'
        '    if platform: qs = qs.filter(platform__iexact=platform)\n'
        '    preview_count = qs.count()\n'
        '\n'
        '    if request.method == "POST":\n'
        '        template = request.POST.get("template", "").strip()\n'
        '        category = request.POST.get("category", "").strip()\n'
        '        country  = request.POST.get("country",  "").strip()\n'
        '        platform = request.POST.get("platform", "").strip()\n'
        '        if not template:\n'
        '            messages.error(request, "Template name is required.")\n'
        '            return redirect("bulk-compose")\n'
        '        qs = Contact.objects.all()\n'
        '        if category: qs = qs.filter(category__name__iexact=category)\n'
        '        if country:  qs = qs.filter(country__iexact=country)\n'
        '        if platform: qs = qs.filter(platform__iexact=platform)\n'
        '        bulk = BulkMessage.objects.create(\n'
        '            template=template,\n'
        '            filter_params={"category": category, "country": country, "platform": platform},\n'
        '            status="sending",\n'
        '            created_by=request.user,\n'
        '        )\n'
        '        from ..services.whatsapp import send_whatsapp\n'
        '        sent = failed = 0\n'
        '        for contact in qs.iterator():\n'
        '            success = send_whatsapp(\n'
        '                to=contact.full_whatsapp,\n'
        '                template=template,\n'
        '                params=[contact.first_name, str(contact.pk)],\n'
        '                contact=contact,\n'
        '            )\n'
        '            if success: sent += 1\n'
        '            else: failed += 1\n'
        '            time.sleep(0.75)\n'
        '        bulk.sent_count   = sent\n'
        '        bulk.failed_count = failed\n'
        '        bulk.status       = "done"\n'
        '        bulk.save()\n'
        '        messages.success(request, f"Bulk send complete. Sent: {sent}  Failed: {failed}")\n'
        '        return redirect("bulk-history")\n'
        '\n'
        '    return render(request, "contacts/bulk_compose.html", {\n'
        '        "preview_count": preview_count,\n'
        '        "filters": {"category": category, "country": country, "platform": platform},\n'
        '    })\n'
        '\n'
        '\n'
        '@login_required(login_url="login")\n'
        'def bulk_history_view(request):\n'
        '    history = BulkMessage.objects.select_related("created_by").order_by("-created_at")\n'
        '    return render(request, "contacts/bulk_history.html", {"history": history})\n'
        '\n'
        '\n'
        '@login_required(login_url="login")\n'
        'def bulk_preview_api(request):\n'
        '    qs = Contact.objects.all()\n'
        '    category = request.GET.get("category", "").strip()\n'
        '    country  = request.GET.get("country",  "").strip()\n'
        '    platform = request.GET.get("platform", "").strip()\n'
        '    if category: qs = qs.filter(category__name__iexact=category)\n'
        '    if country:  qs = qs.filter(country__iexact=country)\n'
        '    if platform: qs = qs.filter(platform__iexact=platform)\n'
        '    return JsonResponse({"count": qs.count()})\n'
        '\n'
        '\n'
        'def service_request_view(request):\n'
        '    if request.method == "POST":\n'
        '        name    = request.POST.get("name",    "").strip()\n'
        '        email   = request.POST.get("email",   "").strip()\n'
        '        phone   = request.POST.get("phone",   "").strip()\n'
        '        budget  = request.POST.get("budget",  "").strip()\n'
        '        notes   = request.POST.get("notes",   "").strip()\n'
        '        category       = request.POST.get("category", "").strip()\n'
        '        country        = request.POST.get("country",  "").strip()\n'
        '        platform       = request.POST.get("platform", "").strip()\n'
        '        follower_range = request.POST.get("follower_range", "").strip()\n'
        '        if not name or not email or not phone:\n'
        '            messages.error(request, "Name, email, and phone are required.")\n'
        '            return redirect("service-request")\n'
        '        sr = ServiceRequest.objects.create(\n'
        '            requester_name  = name,\n'
        '            email           = email,\n'
        '            phone           = phone,\n'
        '            budget          = budget,\n'
        '            notes           = notes,\n'
        '            filter_criteria = {\n'
        '                "category":       category,\n'
        '                "country":        country,\n'
        '                "platform":       platform,\n'
        '                "follower_range": follower_range,\n'
        '            },\n'
        '        )\n'
        '        try:\n'
        '            from django.conf import settings\n'
        '            from ..services.whatsapp import send_whatsapp\n'
        '            admin_phone = getattr(settings, "SK_ADMIN_WHATSAPP", "")\n'
        '            if admin_phone:\n'
        '                send_whatsapp(\n'
        '                    to=admin_phone,\n'
        '                    template="new_service_request",\n'
        '                    params=[name, email, f"#{sr.pk}"],\n'
        '                )\n'
        '        except Exception:\n'
        '            pass\n'
        '        messages.success(request, "Your request has been submitted. We will be in touch shortly.")\n'
        '        return redirect("service-request-thanks")\n'
        '    return render(request, "contacts/service_request.html")\n'
        '\n'
        '\n'
        'def service_request_thanks_view(request):\n'
        '    return render(request, "contacts/service_request_thanks.html")\n'
    )
print("bulk.py written OK")
